apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-k8s-basic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-argocd-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-argocd-application
    spec:
      containers:
      - name: app-argocd-container
        image: 7910trio/app-with-argocd:6dff19f66e4afeb65666963ee2969698adacaaf9
        ports:
          - protocol: TCP
            containerPort: 8080
