apiVersion: v1
kind: Service
metadata:
  name: app-argocd-service
spec:
  selector:
    app.kubernetes.io/name: app-argocd-application
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 31080
    port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-argocd-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-argocd-application
    spec:
      containers:
      - name: app-argocd-container
        image: 7910trio/app-with-argocd:932e205a4a7ea1b7066231b88ea045aff614e4cc
        ports:
          - protocol: TCP
            containerPort: 8080
